site_name: Ciência de Dados Geográficos

docs_dir: src

site_dir: docs

theme:
  name: material

plugins:
    - mkdocs-jupyter:
          include: ["*.ipynb"] # Default: ["*.py", "*.ipynb"]


theme:
  name: material  # Exemplo usando o tema Material for MkDocs
nav:
  - Introdução: index.md
  - Parte 1 - Introdução a Python:
      
      - Capítulo 1: capitulo1.ipynb
      - Capítulo 2: capitulo2.ipynb
      - Capítulo 3: capitulo3.ipynb
  - Parte 2 - Tipos de Dados Geográficos (SIG):
      - Capítulo 4: capitulo4.ipynb
    